go: &go
  build: dev-env
  volumes:
    - .:/go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  working_dir: /go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  environment:
    - GOOS
    - GOARCH
  entrypoint: /usr/local/go/bin/go

package:
  <<: *go
  entrypoint: /opt/lifecycle/package

publish:
  <<: *go
  volumes:
    - $LC_REPO_NETRC:/opt/netrc
  environment:
    - ARTIFACTORY_SERVER
    - ARTIFACTORY_PATH
  entrypoint: /opt/lifecycle/publish

test:
  <<: *go
  entrypoint: /opt/lifecycle/test
  command: "./..."

lint:
  <<: *go
  entrypoint: ["/go/bin/golint"]
  command: "./..."

smoketest:
  build: smoketest
  volumes:
    - .:/opt/project/
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/lc_smoketest:/tmp/lc_smoketest
  environment:
    - COMPOSE_PROJECT_NAME=projectlifecyclesmoketests
    - TMPDIR=/tmp/lc_smoketest
  working_dir: /opt/project
  entrypoint: ["rspec", "--require", "./smoketest/spec_helper.rb", "--format", "documentation"]
  command: ["--pattern", "smoketest/**/*.feature"]
