go: &go
  build: dev-env
  volumes:
    - .:/go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  working_dir: /go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  environment:
    - GOOS
    - GOARCH
  entrypoint: /usr/local/go/bin/go

package:
  <<: *go
  environment:
    - GIT_TAG_NAME
  entrypoint: /opt/lifecycle/package

publish:
  <<: *go
  volumes:
    - $LC_REPO_NETRC:/opt/netrc
    - .:/go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  environment:
    - ARTIFACTORY_SERVER
    - ARTIFACTORY_PATH
  entrypoint: /opt/lifecycle/publish

test:
  <<: *go
  entrypoint: /opt/lifecycle/test
  command: "./..."

lint:
  <<: *go
  entrypoint: ["/go/bin/golint"]
  command: "./..."

blackbox-test: &BLACKBOXTEST
  build: blackbox-test
  volumes:
    - .:/opt/project/
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/lc_blackbox-test:/tmp/lc_blackbox-test
  environment:
    - COMPOSE_PROJECT_NAME=projectlifecycleblackbox
    - TMPDIR=/tmp/lc_blackbox-test
  working_dir: /opt/project
  entrypoint: ["rspec", "--require", "./blackbox-test/spec_helper.rb", "--format", "documentation"]
  command: ["--pattern", "blackbox-test/**/*.feature"]

# Once a new version of lc is available, this section can be removed.
smoketest:
  <<: *BLACKBOXTEST
